<?php

return [
    // Title & Header
    'title' => 'Investor Report - :name',
    'back_to_account' => 'Back to Account',
    'print_report' => 'Print Report',
    'export_pdf' => 'Export PDF',
    'investor_performance_report' => 'Investor Performance Report',
    'account_label' => 'Account',
    'generated_label' => 'Generated',
    'performance_summary' => 'Performance Summary',

    // Key Metrics
    'total_investment' => 'Total Investment',
    'total_profit' => 'Total Profit',
    'roi' => 'ROI',
    'win_rate' => 'Win Rate',

    // Charts
    'investment_distribution' => '📈 Investment Distribution',
    'monthly_performance' => '📊 Monthly Performance',
    'monthly_profit' => 'Monthly Profit',
    'cumulative_profit' => 'Cumulative Profit',

    // Investor Details Table
    'investor_performance_details' => '👥 Investor Performance Details',
    'investor' => 'Investor',
    'initial_investment' => 'Initial Investment',
    'ownership_percentage' => 'Ownership %',
    'profit_share' => 'Profit Share',
    'total_value' => 'Total Value',
    'growth_percentage' => 'Growth %',
    'join_date' => 'Join Date',
    'na' => 'N/A',
    'performance_status' => 'Performance Status',

    // Trading Statistics
    'trading_statistics' => 'Trading Statistics',
    'total_trades' => 'Total Trades',
    'best_trade' => 'Best Trade',
    'worst_trade' => 'Worst Trade',
    'average_trade' => 'Average Trade',

    // profit distribution
    'profit_distribution' => 'Profit Distribution',
    'profit_share_per_investor' => 'Profit Share per Investor',
    'growth_comparison' => 'Growth Comparison',
    'growth_percentage_by_investor' => 'Growth Percentage by Investor',

    // Performance Metrics
    'performance_metrics' => 'Performance Metrics',
    'sharpe_ratio' => 'Sharpe Ratio',
    'profit_factor' => 'Profit Factor',
    'max_drawdown' => 'Max Drawdown',

    // Risk Metrics
    'risk_metrics' => 'Risk Metrics',
    'risk_reward_ratio' => 'Risk/Reward Ratio',
    'recovery_factor' => 'Recovery Factor',
    'expectancy' => 'Expectancy',

    // Profit Distribution Explanation
    'profit_distribution_explanation' => 'Profit Sharing Explanation',
    'profit_distribution_description' => 'Profit share is calculated based on the investors percentage ownership of the total investment.',
    'profit_distribution_description_rumus' => 'The formula for calculating profit share is: Profit Share = (Percentage Ownership / 100) x Total Profit.',
    'profit_distribution_description_example' => 'For example, if an investor owns 25% ownership and the total profit is $10,000, then their profit share is (25/100) x $10,000 = $2,500.',

    // Footer
    'report_footer' => 'Report generated by Journal Trade System | :date',
    'confidential_notice' => 'Confidential - For Investor Review Only',
];
